/*
 * This source file was generated by the Gradle 'init' task
 */
package com.mealplanner;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;

class DatabaseTest {
    // @Test
    // void appHasAGreeting() {
    // App classUnderTest = new App();
    // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    // }

    @Test
    void dbGetDishNotExist() {
        Database testdb = new Database(true);
        assertNull(testdb.getDishByName("Pizza"));
    }

    @Test
    void dbAddDish() {
        Database testdb = new Database(true);
        assertNull(testdb.getDishByName("Pizza"));
        Dish pizza = new Dish("Pizza");
        assertTrue(testdb.addDish(pizza));
        assertEquals(pizza.getName(), testdb.getDishByName("Pizza").getName());
    }

    @Test
    void dbAddDuplicateDish() {
        Database testdb = new Database(true);
        // assertNull(testdb.getDishByName("Pizza"));
        Dish pizza = new Dish("Pizza");
        assertTrue(testdb.addDish(pizza));
        assertEquals(pizza.getName(), testdb.getDishByName("Pizza").getName());
        assertFalse(testdb.addDish(pizza));
    }

    @Test
    void dbUpdateDish() {
        Database testdb = new Database(true);
        assertNull(testdb.getDishByName("Pizza"));
        Dish pizza = new Dish("Pizza");
        assertTrue(testdb.addDish(pizza));
        Dish fish = new Dish("Fish");
        assertTrue(testdb.updateDish(pizza, fish));
        assertEquals(fish.getName(), testdb.getDishByName("Fish").getName());
    }

    @Test
    void dbGetAllDishes() {
        Database testdb = new Database(true);
        Dish pizza = new Dish("Pizza");
        Dish fish = new Dish("Fish");
        Dish taco = new Dish("Taco");
        assertTrue(testdb.addDish(pizza));
        assertTrue(testdb.addDish(fish));
        assertTrue(testdb.addDish(taco));
        ArrayList<Dish> allDishes = testdb.getAllDishes();
        assertEquals(3, allDishes.size());
    }
}
